repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
      hooks:
        - id: markdownlint

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black

  - repo: https://github.com/GoogleContainerTools/kaniko
    rev: v1.9.0
    hooks:
      - id: dockerfile-lint

  - repo: https://github.com/pre-commit/mirrors-golangci-lint
    rev: v1.50.0
    hooks:
      - id: golangci-lint

  - repo: https://github.com/mikebattaini/pre-commit-makefile
    rev: v0.1.0
    hooks:
      - id: makefile-lint

  - repo: https://github.com/harness/k8s-operator
    rev: v1.0.0
    hooks:
      - id: k8s-lint

  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
      rev: v0.0.8
      hooks:
          - id: k8svalidate
            files: .yml$

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1 # or other specific tag
    hooks:
      - id: yamlfmt