apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hasura-jwt.fullname" . }}-deployment
  labels:
    {{- include "hasura-jwt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hasura-jwt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hasura-jwt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              {{- if kindIs "map" $value }}
              {{- toYaml $value | nindent 14 }}
              {{- else }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
