ingress:
  enabled: true
  hostName: "hasura.docker.internal"
  ingressClassName: "nginx"
  annotations: {}

postgres:
  enabled: true

  auth:
    username: postgres
    password: postgrespassword
    database: public

  persistence:
    enabled: true
    size: 1Gi

secret:
  adminSecret: "my-secret"
  jwtSecret: {"type": "HS256", "key": "this-is-a-generic-HS256-secret-key-and-you-should-really-change-it"}
  unauthorizedRole: "anonymous"
  metadataDbUrl: postgres://postgres:postgrespassword@hasura-postgres:5432/public
  
  extraSecrets:
    DATA_DATABASE_URL: postgres://postgres:postgrespassword@hasura-postgres:5432/public

extraEnvs:
  - name: JWT_URL
    value: http://hasura-jwt:3000

#config:
#  metadataOnly: false
#  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@hasura-postgres:5432/public