name: Release Helm Chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/hasura-jwt/**'

env:
  REGISTRY: ghcr.io

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: helm package charts/hasura-jwt -d /tmp/helm-charts

      - name: Push Helm chart to GHCR
        run: |
          CHART_PACKAGE=$(ls /tmp/helm-charts/hasura-jwt-*.tgz)
          helm push $CHART_PACKAGE oci://${{ env.REGISTRY }}/${{ github.repository_owner }}
